typography_spectrum: 0.2384958218317479
content_rating:
  adult: false
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.21642948524095118
  lightness: 0.03538491460494697
  saturation: 0.7783540829550475
  rhythmicContrast: 0.6751957326196134
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5592402019537985
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Sasha vom Dorp
  email: 8ripple@gmail.com
  url: www.soundbendinglight.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/927dc0ae-7910-402b-8984-c463fd984022.jpg
name: Sound Bending Light
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/506c975b-09b4-426f-aa57-ae4f0e21bd88.jpg
purpose: []
