name: Sound Bending Light
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/506c975b-09b4-426f-aa57-ae4f0e21bd88.jpg
layout_spectrum: 0.13497
typography_spectrum: 0.87282
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/927dc0ae-7910-402b-8984-c463fd984022.jpg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
  brandStrength: 0.8376054579857737
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
